/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'muhuk' at '21/5/16 5:17 PM' with Gradle 2.13
 *
 * @author muhuk, @date 21/5/16 5:17 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
